replicaCount: 1

image:
  repository: maxmorhardt/topfilms-auth-api
  tag: '1.0.0'
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: auth.topfilms.co
      paths:
        - path: /
          pathType: Prefix
  tls: 
   - secretName: auth-api-cert
     hosts:
       - auth.topfilms.co

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi