apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-api.fullname" . }}
  labels:
    {{- include "auth-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "auth-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "auth-api.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: FRONTEND_URL
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: frontendUrl
          - name: AUTHENTICATION_API_URL
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: authApiUrl
          - name: AUTHENTICATION_API_PORT
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: authApiPort
          - name: SUPER_TOKENS_CORE_URL
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: supertokensCoreUrl
          - name: SUPER_TOKENS_CORE_API_KEY
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: apiKey
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: googleClientId
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: googleClientSecret
          - name: GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: githubClientId
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: githubClientSecret
          - name: DISCORD_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: discordClientId
          - name: DISCORD_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-env
                key: discordClientSecret
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}